name = "JungleTree"
motd = "A JungleTree Server"

[server]
host = "0.0.0.0"
port = 25565

[console.rcon]
enabled = false

[console.web]
enabled = false
host = "127.0.0.1"
port = 3000

[players]
max = 1000
